TEST 1

//SNOW deployment2 for, cg3-Phase 2, RITM0016253 - https://vptdev.service-now.com/sc_req_item.do?sys_id=420266d51bacf1106f7976ae034bcb10

- name: tenant
  value: prod
- name: subscriptionId
  value: VP-TEST-CORE
- name: adoServiceConnectionName
  value: VP-TEST-CORE_devops_connection_managedid