TEST 

# SNOW deployment for, ocs-Phase 1, RITM0017257 - https://vptdev.service-now.com/sc_req_item.do?sys_id=e8a47f2ddbf535505b98496d139619e3

- name: sub_type
  value: 'cust'
- name: tla
  value: 'fit'
- name: deployment_env
  value: 'cts'
- name: vpt_competency
  value: ''
- name: solutionsuite
  value: 'ocs'
- name: size
  value: 'Medium'
- name: cleanup
  value: 'false'