TEST 

# SNOW deployment for, nss-Phase 2, RITM0017898 - https://vptdev.service-now.com/sc_req_item.do?sys_id=c61cb42bdb7bf5105b98496d13961997

- name: sub_type
  value: 'cust'
- name: tla
  value: 'bxs'
- name: deployment_env
  value: 'prod'
- name: vpt_competency
  value: ''
- name: solutionsuite
  value: 'nss'
- name: size
  value: 'Small'
- name: cleanup
  value: 'false'